// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       uint        `orm:"id,primary" json:"id"`       // ID
	Passport string      `orm:"passport"   json:"passport"` //
	Password string      `orm:"password"   json:"password"` //
	Nickname string      `orm:"nickname"   json:"nickname"` //
	CreateAt *gtime.Time `orm:"create_at"  json:"createAt"` //
	UpdateAt *gtime.Time `orm:"update_at"  json:"updateAt"` //
}


// Account is the golang structure for table account.
type Account struct {
	Account         string      `orm:"account,primary"  json:"account"`         //
	Balance         int         `orm:"balance"          json:"balance"`         //
	Interest        float64     `orm:"interest"         json:"interest"`        //
	TransactionTime *gtime.Time `orm:"transaction_time" json:"transactionTime"` //
	CreateAt        *gtime.Time `orm:"create_at"        json:"createAt"`        //
	UpdateAt        *gtime.Time `orm:"update_at"        json:"updateAt"`        //
}
