// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/app/dao/internal"
)

// accountDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type accountDao struct {
	*internal.AccountDao
}

var (
	// Account is globally public accessible object for table account operations.
	Account accountDao
)

func init() {
	Account = accountDao{
		internal.NewAccountDao(),
	}
}

// Fill with you ideas below.
